# Generated by Django 3.2.13 on 2022-10-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20221006_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Classe'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses'},
        ),
    ]
