# Generated by Django 3.2.13 on 2022-10-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20221006_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course'},
        ),
    ]
