# Generated by Django 3.2.13 on 2022-10-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
    ]
