# Generated by Django 3.2.13 on 2022-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='classes',
            field=models.FileField(default='None', upload_to='classes'),
        ),
    ]
