# Generated by Django 3.2.13 on 2022-10-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20221007_1820'),
        ('quiz', '0002_question_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.classes'),
        ),
    ]
